Added a new meme.
LewisProjects/Ogiroid pull request #59
Opened 2022-11-13 21:05 UTC by nxtCP

2022-11-13 21:09 UTC, OpenSourceSimon requested changes
Command with spaces don't work according to Levani

2022-11-13 21:09 UTC, OpenSourceSimon commented on cogs/Memes.py
> +    @commands.slash_command(name="/boners with lewis", description="Boners with lewis")
```suggestion
    @commands.slash_command(name="/bonerswithlewis", description="Boners with lewis")
```

2022-11-13 21:13 UTC, OpenSourceSimon approved these changes
Looks good to me, @LevaniVashadze Can you review? When we're going to merge, make sure to squash merge because of the many commits.

2022-11-14 04:30 UTC, JasonLovesDoggo commented
@nxtCP has it been tested?

2022-11-14 04:31 UTC, JasonLovesDoggo commented
> @nxtCP has it been tested? 

Also change cmd name to lewisboner

2022-11-14 04:32 UTC, JasonLovesDoggo requested changes

2022-11-14 04:32 UTC, JasonLovesDoggo commented on cogs/Memes.py
> +    @commands.slash_command(name="/bonerswithlewis", description="Boners with lewis")
Change cmd name to lewisboner other than that I approve

2022-11-14 06:53 UTC, OpenSourceSimon reviewed
Suggested change from Jason

2022-11-14 06:53 UTC, OpenSourceSimon commented on cogs/Memes.py
> +    @commands.slash_command(name="/bonerswithlewis", description="Boners with lewis")
```suggestion
    @commands.slash_command(name="/lewisboner", description="Boners with lewis")
```

2022-11-14 09:28 UTC, ImmaHarry commented
Guys change the name, its NSFW. We cannot have a rule going against NSFW content & implement an NSFW feature at the same time, even though its a joke. Please use alternative wording for this command, I think it'd be okay to have it send that picture but the command name needs to be something else. End of discussion here.

2022-11-14 10:03 UTC, OpenSourceSimon commented
> Guys change the name, its NSFW. We cannot have a rule going against NSFW content & implement an NSFW feature at the same time, even though its a joke. Please use alternative wording for this command, I think it'd be okay to have it send that picture but the command name needs to be something else. End of discussion here.
> 
> PS: It also creates a wrong impression for the time/new users on the server or of the bot.

Haven't seen it in that way, I totally agree with you

2022-11-14 15:46 UTC, LevaniVashadze commented
> 

gotta agree on this one i also think we dont need to have such stuff in the bot since it just turns into a bit of spam and the onlyfans command was a fun meme and many of them ruins the purpose kind of

2022-11-14 15:46 UTC, LevaniVashadze commented
also you could just go to #starboard or create a tag and would see that funny thing

2022-11-14 15:49 UTC, closed without merging

2022-11-14 15:50 UTC, JasonLovesDoggo commented
Can be implemented via tags directly, might add a admin only /tag a_alias add cmd that gives the tag a apex level name